-- CREATE DATABASE luna_dev_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- CREATE USER 'luna_dev_user'@'%' IDENTIFIED BY 'luna_dev_pass'; 
-- GRANT ALL PRIVILEGES ON luna_dev_db.* TO 'luna_dev_user'@'%' IDENTIFIED BY 'luna_dev_pass'; 
-- FLUSH PRIVILEGES;
